const Images = {
  // Intro Images
  INTRO_IMAGE: require('../assets/images/IntroScreen_01.png'),
  INTRO_IMAGE_02: require('../assets/images/IntroScreen_02.png'),
  BACK_IMAGE: require('../assets/images/backArrow.png'),
  LOGIN_IMAGE: require('../assets/images/LoginImage.png'),
  OTP_IMAGE: require('../assets/images/OtpImage.png'),
  EMAIL_IMAGE: require('../assets/images/Store.png'),
  FORGET_PASSWORD_IMAGE: require('../assets/images/ForgotPassword.png'),
  EYE_IMAGE: require('../assets/images/eye.png'),
  EYE_HIDE_IMAGE: require('../assets/images/eye.png'),
  CHANGE_PASSWORD_IMAGE: require('../assets/images/ChangePassword.png'),
  CAMERA_IMAGE: require('../assets/images/Camera.png'),
  MENU_ICON_IMAGE: require('../assets/images/MenuHeader_01.png'),
  LOGO_ICON_IMAGE: require('../assets/images/mainLogo.png'),
  CHAT_ICON_IMAGE: require('../assets/images/chat.png'),
  NOTIFICATION_ICON_IMAGE: require('../assets/images/Notification.png'),
  ADD_IMAGE: require('../assets/images/addImage.png'),
  DUMMY_STORY_IMAGE: require('../assets/images/dummyStory.png'),
  DUMMY_PROFILE_IMAGE: require('../assets/images/dummyStory.png'),
  DUMMY_POST_IMAGE: require('../assets/images/PostImageMain.png'),
  THREE_DOT_POST_IMAGE: require('../assets/images/Ellipsis.png'),
  STAR_IMAGE: require('../assets/images/Star.png'),
  VIDEO_CALLING_BACKGROUND: require('../assets/images/VideoCalling.png'),
  SELECTED_HOME: require('../assets/images/dummyImages/SelectedHome.png'),
  UNSELECTED_HOME: require('../assets/images/dummyImages/UnselectedHome.png'),
  SELECTED_TWEET: require('../assets/images/TweetImage.png'),
  UNSELECTED_TWEET: require('../assets/images/TweetImage.png'),
  SELECTED_REELS: require('../assets/images/ReelImgae.png'),
  UNSELECTED_REELS: require('../assets/images/ReelImgae.png'),
  SELECTED_PROFILE: require('../assets/images/dummyImages/Male_User.png'),
  UNSELECTED_PROFILE: require('../assets/images/dummyImages/bxs_user.png'),
  CAMERA: require('../assets/images/dummyImages/takePicture.png'),
  SHARE_IMAGE: require('../assets/images/ShareImage.png'),
  CAMERA_ICON: require('../assets/images/UploadQuestion.png'),
  HEART_IMAGE: require('../assets/images/HeartImage.png'),
  FOLLOW_DUMMY_IMAGE: require('../assets/images/FollowScreen.png'),
  CAR_IMAGE_DUMMY: require('../assets/images/MyMarketPlaceImages/car_image.png'),
  DUMMY_IMAGE_3: require('../assets/images/MyMarketPlaceImages/dummt_image_3.png'),
  DUMMY_IMAGE_2: require('../assets/images/MyMarketPlaceImages/dummy_image_2.png'),
  DUMMY_IMAGE_1: require('../assets/images/MyMarketPlaceImages/dummy_images_1.png'),
  HOUSE_IMAGE_DUMMY: require('../assets/images/MyMarketPlaceImages/house_image.png'),
  // new icon
  HOME_NEW_ICON: require('../assets/images/newIcons/homeNewIcon.png'),
  HOME_NEW_SELECTED_ICON: require('../assets/images/newIcons/homeNewSelectedIcon.png'),
  REELS_NEW_ICON: require('../assets/images/newIcons/reelsIcon.png'),
  VIDEO_NEW_ICON: require('../assets/images/newIcons/videoIcon.png'),
  PROFILE_NEW_ICON: require('../assets/images/newIcons/profileIcon.png'),
  YELLOW_SEARCH: require('../assets/images/yellowSearch.png'),

  // settings Icon
  SETTING_GROUP_ICON: require('../assets/images/settingIcons/group.png'),
  FRIENDS_GROUP_ICON: require('../assets/images/settingIcons/friends.png'),
  CHANGE_PASS_GROUP_ICON: require('../assets/images/settingIcons/icon-1.png'),
  NOTIFICATION_GROUP_ICON: require('../assets/images/settingIcons/notifications.png'),
  PRIVACY_GROUP_ICON: require('../assets/images/settingIcons/privacy.png'),
  SIGN_OUT_GROUP_ICON: require('../assets/images/settingIcons/logout.png'),
  PAYMENT_ICON: require('../assets/images/settingIcons/payment.png'),
  TICK_ICON: require('../assets/images/checklist.png'),
  STORY_NEW_ICON: require('../assets/images/homeIcons/Story.png'),
  UNLIKE_ICON: require('../assets/images/homeIcons/Like.png'),
  LOADING: require('../assets/images/CLICKNTOKK.png'),
  THUMB_UP: require('../assets/images/thumbsUp.png')

  // BUY_STAR_GROUP_ICON: require('../assets/images/settingIcons/yellowSearch.png'),
  // REDEEM_START_GROUP_ICON: require('../assets/images/settingIcons/yellowSearch.png'),
  // DELETE_GROUP_ICON: require('../assets/images/settingIcons/yellowSearch.png')

}
export default Images
